services:
  postgres:
    hostname: postgres
    restart: unless-stopped
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nutrition_tracking_api_test
