"""add_password_hash_and_nullable_access_token_to_user

Revision ID: 86c8e8611f1b
Revises: 41b4aa119d4d
Create Date: 2026-03-23 23:19:07.983562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86c8e8611f1b'
down_revision = '41b4aa119d4d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_token',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('jti', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_refresh_token_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_token'))
    )
    op.create_index(op.f('ix_refresh_token_jti'), 'refresh_token', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_token_user_id'), 'refresh_token', ['user_id'], unique=False)
    op.add_column('user', sa.Column('password_hash', sa.String(), nullable=True))
    op.alter_column('user', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'access_token',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('user', 'password_hash')
    op.drop_index(op.f('ix_refresh_token_user_id'), table_name='refresh_token')
    op.drop_index(op.f('ix_refresh_token_jti'), table_name='refresh_token')
    op.drop_table('refresh_token')
    # ### end Alembic commands ###
