"""add food_item model

Revision ID: 39dd301506b5
Revises: f4bca3c6c3f3
Create Date: 2026-03-29 17:37:45.634659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dd301506b5'
down_revision = 'f4bca3c6c3f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_item',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('calories_per_100g', sa.Float(), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('creator_id', sa.Uuid(), nullable=True),
    sa.Column('modifier_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_food_item_creator_id_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['modifier_id'], ['user.id'], name=op.f('fk_food_item_modifier_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_item')),
    sa.UniqueConstraint('barcode', name=op.f('uq_food_item_barcode'))
    )
    op.create_index(op.f('ix_food_item_name'), 'food_item', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_food_item_name'), table_name='food_item')
    op.drop_table('food_item')
    # ### end Alembic commands ###
