"""add User model

Revision ID: 99cb4366c47f
Revises:
Create Date: 2026-02-19 17:54:44.842548

"""

from alembic import op
import sqlalchemy as sa

from datetime import datetime
from nutrition_tracking_api.settings import settings

# revision identifiers, used by Alembic.
revision = "99cb4366c47f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    user_table = op.create_table(
        "user",
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("access_token_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_service_user", sa.Boolean(), nullable=False),
        sa.Column("ad_login", sa.String(), nullable=True),
        sa.Column("master_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("access_token"),
    )
    op.bulk_insert(
        user_table,
        [
            {
                "username": "admin",
                "access_token": f"{settings.admin_token}",
                "is_service_user": True,
                "is_superuser": True,
                "id": "98c4e353-93ae-4842-9f94-4be8b5164b58",
                "created_at": datetime.now(),
                "updated_at": datetime.now(),
            }
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
