"""remove master_id and ad_login from user

Revision ID: f4bca3c6c3f3
Revises: 7ea4db84a90c
Create Date: 2026-03-29 13:24:23.794875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4bca3c6c3f3'
down_revision = '7ea4db84a90c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'master_id')
    op.drop_column('user', 'ad_login')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ad_login', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('master_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
