"""add meal_entry and meal_food_item models

Revision ID: a549873667e3
Revises: 39dd301506b5
Create Date: 2026-03-29 19:09:21.094476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a549873667e3'
down_revision = '39dd301506b5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meal_entry',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='mealtypeenum', native_enum=False, length=50), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_meal_entry_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_entry')),
    sa.UniqueConstraint('user_id', 'date', 'meal_type', name='_unique_user_date_meal_type')
    )
    op.create_index(op.f('ix_meal_entry_user_id'), 'meal_entry', ['user_id'], unique=False)
    op.create_table('meal_food_item',
    sa.Column('meal_entry_id', sa.Uuid(), nullable=False),
    sa.Column('food_item_id', sa.Uuid(), nullable=True),
    sa.Column('custom_name', sa.String(), nullable=True),
    sa.Column('amount_g', sa.Float(), nullable=False),
    sa.Column('calories_kcal', sa.Float(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['food_item_id'], ['food_item.id'], name=op.f('fk_meal_food_item_food_item_id_food_item'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['meal_entry_id'], ['meal_entry.id'], name=op.f('fk_meal_food_item_meal_entry_id_meal_entry'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meal_food_item'))
    )
    op.create_index(op.f('ix_meal_food_item_food_item_id'), 'meal_food_item', ['food_item_id'], unique=False)
    op.create_index(op.f('ix_meal_food_item_meal_entry_id'), 'meal_food_item', ['meal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meal_food_item_meal_entry_id'), table_name='meal_food_item')
    op.drop_index(op.f('ix_meal_food_item_food_item_id'), table_name='meal_food_item')
    op.drop_table('meal_food_item')
    op.drop_index(op.f('ix_meal_entry_user_id'), table_name='meal_entry')
    op.drop_table('meal_entry')
    # ### end Alembic commands ###
