"""add_user_profile_fields

Revision ID: b2a7c26f5f12
Revises: 53e6b61a110d
Create Date: 2026-04-02 00:16:09.759995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a7c26f5f12'
down_revision = '53e6b61a110d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female', 'other', name='genderenum', native_enum=False, length=50), nullable=True))
    op.add_column('user', sa.Column('height_cm', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('weight_kg', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('activity_level', sa.Enum('sedentary', 'lightly_active', 'moderately_active', 'very_active', 'extra_active', name='activitylevelenum', native_enum=False, length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'activity_level')
    op.drop_column('user', 'weight_kg')
    op.drop_column('user', 'height_cm')
    op.drop_column('user', 'gender')
    op.drop_column('user', 'birth_date')
    # ### end Alembic commands ###
