"""add creator and modifier

Revision ID: 41b4aa119d4d
Revises: a1b2c3d4e5f6
Create Date: 2026-02-27 17:07:51.648226

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41b4aa119d4d"
down_revision = "a1b2c3d4e5f6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add creator and modifier
    op.add_column("policy", sa.Column("creator_id", sa.Uuid(), nullable=True))
    op.add_column("policy", sa.Column("modifier_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_policy_modifier_id_user"), "policy", "user", ["modifier_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(
        op.f("fk_policy_creator_id_user"), "policy", "user", ["creator_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("role", sa.Column("creator_id", sa.Uuid(), nullable=True))
    op.add_column("role", sa.Column("modifier_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_role_modifier_id_user"), "role", "user", ["modifier_id"], ["id"], ondelete="SET NULL"
    )
    op.create_foreign_key(op.f("fk_role_creator_id_user"), "role", "user", ["creator_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_role_creator_id_user"), "role", type_="foreignkey")
    op.drop_constraint(op.f("fk_role_modifier_id_user"), "role", type_="foreignkey")
    op.drop_column("role", "modifier_id")
    op.drop_column("role", "creator_id")
    op.drop_constraint(op.f("fk_policy_creator_id_user"), "policy", type_="foreignkey")
    op.drop_constraint(op.f("fk_policy_modifier_id_user"), "policy", type_="foreignkey")
    op.drop_column("policy", "modifier_id")
    op.drop_column("policy", "creator_id")
    # ### end Alembic commands ###
