"""Auth roles policies

Revision ID: 784b8226c7b4
Revises: 99cb4366c47f
Create Date: 2026-02-20 14:00:05.131069

"""

import uuid
from datetime import datetime

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "784b8226c7b4"
down_revision = "99cb4366c47f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    policy_table = op.create_table(
        "policy",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("targets", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("actions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("matchers", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("options", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    role_table = op.create_table(
        "role",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "ix_unique_default", "role", ["is_default"], unique=True, postgresql_where=sa.text("is_default = true")
    )
    role_policy_table = op.create_table(
        "role_policy",
        sa.Column("policy_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["policy.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["role.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("policy_id", "role_id", name="_unique_policy_role"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "role_id", name="_unique_user_role"),
    )
    op.create_index(op.f("ix_user_roles_role_id"), "user_roles", ["role_id"], unique=False)
    op.create_index(op.f("ix_user_roles_user_id"), "user_roles", ["user_id"], unique=False)
    op.add_column("user", sa.Column("full_name", sa.String(), nullable=True))

    # Seed: дефолтная роль и nutrition политики
    now = datetime.now()
    default_role_id = uuid.uuid4()

    op.bulk_insert(
        role_table,
        [
            {
                "id": default_role_id,
                "name": "user",
                "description": "Дефолтная роль для всех пользователей",
                "is_default": True,
                "created_at": now,
                "updated_at": now,
            }
        ],
    )

    user_matcher = [{"field": "user_id", "condition": "eq", "value": "$user.id"}]
    meal_entry_matcher = [{"field": "meal_entry.user_id", "condition": "eq", "value": "$user.id"}]

    policies = [
        {
            "id": uuid.uuid4(),
            "name": "nutrition-goals-access",
            "description": "Доступ к целям по КБЖУ (только свои)",
            "targets": ["/goals/", "/goals/{object_id}"],
            "actions": ["GET", "POST", "PATCH", "DELETE"],
            "matchers": user_matcher,
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "nutrition-meals-access",
            "description": "Доступ к приёмам пищи (только свои)",
            "targets": ["/meals/", "/meals/{object_id}", "/meals/{object_id}/items/"],
            "actions": ["GET", "POST", "PATCH", "DELETE"],
            "matchers": user_matcher,
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "nutrition-meal-items-access",
            "description": "Доступ к продуктам в приёмах пищи (через meal_entry)",
            "targets": ["/meal-items/", "/meal-items/{object_id}"],
            "actions": ["GET", "POST", "PATCH", "DELETE"],
            "matchers": meal_entry_matcher,
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "nutrition-foods-read-access",
            "description": "Чтение и добавление продуктов (все пользователи)",
            "targets": ["/foods/", "/foods/{object_id}"],
            "actions": ["GET", "POST"],
            "matchers": None,
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "nutrition-foods-write-access",
            "description": "Редактирование и удаление продуктов (только создатель)",
            "targets": ["/foods/", "/foods/{object_id}"],
            "actions": ["PATCH", "DELETE"],
            "matchers": [{"field": "creator_id", "condition": "eq", "value": "$user.id"}],
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "nutrition-weight-access",
            "description": "Доступ к истории веса (только свои)",
            "targets": ["/weight-logs/", "/weight-logs/{object_id}"],
            "actions": ["GET", "POST", "PATCH", "DELETE"],
            "matchers": user_matcher,
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
        {
            "id": uuid.uuid4(),
            "name": "user-profile-access",
            "description": "Доступ к профилю текущего пользователя",
            "targets": ["/auth/users/me/"],
            "actions": ["GET", "PATCH"],
            "matchers": None,
            "options": None,
            "created_at": now,
            "updated_at": now,
        },
    ]

    op.bulk_insert(policy_table, policies)

    op.bulk_insert(
        role_policy_table,
        [
            {
                "id": uuid.uuid4(),
                "policy_id": policy["id"],
                "role_id": default_role_id,
                "created_at": now,
                "updated_at": now,
            }
            for policy in policies
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "full_name")
    op.drop_index(op.f("ix_user_roles_user_id"), table_name="user_roles")
    op.drop_index(op.f("ix_user_roles_role_id"), table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_table("role_policy")
    op.drop_index("ix_unique_default", table_name="role", postgresql_where=sa.text("is_default = true"))
    op.drop_table("role")
    op.drop_table("policy")
    # ### end Alembic commands ###
