"""add_unique_constraint_to_user_username

Revision ID: 7ea4db84a90c
Revises: 86c8e8611f1b
Create Date: 2026-03-23 23:43:24.438253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ea4db84a90c'
down_revision = '86c8e8611f1b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_user_username'), 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_user_username'), 'user', type_='unique')
    # ### end Alembic commands ###
